api_version = "2025-07"

[[extensions]]
name = "t:name"
handle = "subscription-validate"
type = "function"
uid = "78c8bfd3-27e1-e07b-b3b7-bd2a540e97f8f84f1b4e"
description = "Valida as assinatura feitas pelo app Appstle"

  [[extensions.targeting]]
  target = "cart.validations.generate.run"
  input_query = "src/cart_validations_generate_run.graphql"
  export = "cart-validations-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
